easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - username
          - email
          - enabled
          - lastLogin
          # if administrators are allowed to edit users' passwords and roles, add this:
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
